# .streamlit/secrets.toml

[passwords]
# Follow the rule: username = "password"
abdel.boucekine = "9YhjajPMnC"
antoine.arnail = "5tU8N48aL1"
remi.duheille = "Sc0f3GhcPo"
martin.chombart = "u0AuQmzfsx"
romain.devismes = "0kIFgtu9fe"
